# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggy', '0003_auto_20170317_1930'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
