# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_auto_20170320_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='secret_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='secrets.Secret'),
        ),
    ]
