# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170320_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='secret_id',
            new_name='secret',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
