# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170318_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_enrolled', to='loggy.User'),
        ),
    ]
